const paragraphs = [
    
    "You have the right to work, but for the work's sake only. You have no right to the fruits of work. Desire for the fruits of work must never be your motive in working. Never give way to laziness, either.Perform every action with you heart fixed on the Supreme Lord. Renounce attachment to the fruits. Be even-tempered in success and failure: for it is this evenness of temper which is meant by yoga.Work done with anxiety about results is far inferior to work done without such anxiety, in the calm of self-surrender. Seek refuge in the knowledge of Brahma. They who work selfishly for results are miserable.",
    "When meditation is mastered,The mind is unwavering like the Flame of a lamp in a windless place.In the still mind,In the depths of meditation,The Self reveals itself. Beholding the SelfBy means of the Self,An aspirant knows theJoy and peace of complete fulfillment.Having attained thatAbiding joy beyond the senses,Revealed in the stilled mind,He never swerves from the eternal truth.Strive constantly to serve the welfare of the world; by devotion to selfless work one attains the supreme goal of life.",
    "Be fearless and pure; never waiver in your determination or your dedication to the spiritual life. Give freely. Be self-controlled,sincere, truthful, loving,and full of the desire to serve.Realize the truth of the scriptures; learn to be detached and to take joy in renunciation. Do not get angry or harm any living creature but be compassionate and gentle;show good will to all. Cultivate vigor, patience, will purity; avoid malice and pride then, Arjuna, you will achieve your divine destiny.",
    "Krishna says: Arjuna, I am the taste of pure water and the radiance of the sun and moon. I am the sacred word and the sound heard in air, and the courage of human beings. I am the sweet fragrance in the earth and the radiance of fire; I am the life in every creature and the striving of the spiritual aspirant When a man dwells on the pleasure of sense, attraction for them arises in him. From attraction arises desire, the lust of possession, and this leads to passion, to anger.From passion comes confusion of mind, then loss of remembrance, the forgetting of duty. From this loss comes the ruin of reason, and the ruin of reason leads man to destruction.",
    "Every selfless act, Arjuna, is born from Brahman, the eternal, infinite Godhead. He is present in every act of service. All life turns on this law, O Arjuna. Whoever violates it, indulging his senses for his own pleasure and ignoring the needs of others, has wasted his life. But those who realize he Self are always satisfied. Having found the source of joy and fulfillment, they no longer seek happiness from the external world. They have nothing to gain or lose by any action; neither people nor things can affect their security. Strive constantly to serve the welfare of the world; by devotion to selfless work one attains the supreme goal of life.",
    "Being surrounded by supportive individuals is one of the finest ways to build strength. Family, friends, or even coworkers may be among them. They can provide us with the inspiration and drive we require to persevere in trying circumstances. Role models can serve as sources of inspiration as well. These are individuals who have previously shown courage and strength in their lives. We can learn how to be brave by reading about their experiences. Finally, we can read about other people’s experiences to get insight. Numerous books and articles about courage have been produced, and these can be valuable sources of knowledge and inspiration.",
    "A motivational speech can be a powerful tool to uplift and empower people. It serves as a catalyst for change, encouraging individuals to step out of their comfort zones and pursue their dreams. When delivered effectively, a motivational speech has the potential to ignite a fire within individuals, pushing them to overcome obstacles and achieve greatness. One of the key elements of motivational speech topics is its ability to resonate with the audience. By sharing personal experiences and relatable stories, speakers can establish a connection with their listeners, making the message more impactful and inspiring.",
    "My dear Arjuna, how have these impurities come upon you? They are not at all befitting a man who knows the value of life. They lead not to higher planets, but to infamy. O son of Prtha, do not yield to this degrading impotence, that it does not become you. Give up such petty weakness of heart and arise, O chastiser of the enemy. Do your work with the welfare of others always in mind.Strive constantly to serve the welfare of the world; by devotion to selfless work one attains the supreme goal of life."
];